alter table vl_appendix_regimen add treatmentStatusID mediumint unsigned not null after position;
create index treatmentStatusIDIndex on vl_appendix_regimen (treatmentStatusID);
create index treatmentStatusIDIndex on vl_samples (treatmentStatusID);
create index currentRegimenIDIndex on vl_samples (currentRegimenID);
create index arvAdherenceIDIndex on vl_samples (arvAdherenceID);
create index reasonForFailureIDIndex on vl_samples (reasonForFailureID);
create index sampleTypeIDIndex on vl_samples (sampleTypeID);
create index tbTreatmentPhaseIDIndex on vl_samples (tbTreatmentPhaseID);
create index treatmentInitiationIDIndex on vl_samples (treatmentInitiationID);
create index viralLoadTestingIDIndex on vl_samples (viralLoadTestingID);
create index outcomeReasonsIDIndex on vl_samples_verify (outcomeReasonsID);
